import { Database } from "@/types/supabase";

type Product = Database['public']['Tables']['products']['Row'];

export const CATEGORIES = [
    { id: 'fruits', name: 'פירות', slug: 'fruits' },
    { id: 'vegetables', name: 'ירקות', slug: 'vegetables' },
    { id: 'new', name: 'חדש על המדף', slug: 'new' },
    { id: 'dairy', name: 'מקרר, חלב וביצים', slug: 'dairy-eggs' },
    { id: 'bakery', name: 'המאפייה', slug: 'bakery' },
    { id: 'pantry', name: 'המזווה', slug: 'pantry' },
    { id: 'deli', name: 'המעדנייה', slug: 'deli' },
    { id: 'snacks', name: 'חטיפים ומשקאות', slug: 'snacks' },
    { id: 'health', name: 'בריאות', slug: 'health' },
    { id: 'home', name: 'לבית ולמטבח', slug: 'home' },
    { id: 'kids', name: 'ילדים', slug: 'kids' },
    { id: 'winter', name: 'חורף חם', slug: 'winter' },
    { id: 'specials', name: 'מבצעים', slug: 'specials' },
];

export const MOCK_PRODUCTS: Product[] = [
    // Fruits
    {
        id: "f1",
        name: "תות שדה - מארז 1 ק״ג",
        slug: "strawberry-pack",
        description: "תות שדה מתוק ואדום, טרי מהשדה.",
        price: 49.90,
        unit_type: "unit",
        stock_quantity: 50,
        image_url: "https://images.unsplash.com/photo-1610832958506-aa56368176cf?auto=format&fit=crop&q=80&w=800",
        category_id: "fruits",
        is_active: true,
        is_on_sale: true,
        sale_price: null,
        created_at: new Date().toISOString(),
    },
    {
        id: "f2",
        name: "אגס ישראלי",
        slug: "israeli-pear",
        description: "אגס עסיסי ומתוק מתוצרת הארץ.",
        price: 24.90,
        unit_type: "kg",
        stock_quantity: 100,
        image_url: "https://images.unsplash.com/photo-1610832958506-aa56368176cf?auto=format&fit=crop&q=80&w=800",
        category_id: "fruits",
        is_active: true,
        is_on_sale: false,
        sale_price: null,
        created_at: new Date().toISOString(),
    },
    {
        id: "f3",
        name: "קלמנטינה אור",
        slug: "clementine-or",
        description: "קלמנטינה ללא גרעינים, מתוקה וקלה לקילוף.",
        price: 19.90,
        unit_type: "kg",
        stock_quantity: 100,
        image_url: "https://images.unsplash.com/photo-1610832958506-aa56368176cf?auto=format&fit=crop&q=80&w=800",
        category_id: "fruits",
        is_active: true,
        is_on_sale: false,
        sale_price: null,
        created_at: new Date().toISOString(),
    },

    // Vegetables
    {
        id: "v1",
        name: "עגבניות סופי",
        slug: "tomato-maggie",
        description: "עגבניות בטעם של פעם, אדומות ובשרניות.",
        price: 29.90,
        unit_type: "kg",
        stock_quantity: 80,
        image_url: "https://images.unsplash.com/photo-1610832958506-aa56368176cf?auto=format&fit=crop&q=80&w=800",
        category_id: "vegetables",
        is_active: true,
        is_on_sale: true,
        sale_price: 24.90,
        created_at: new Date().toISOString(),
    },
    {
        id: "v2",
        name: "כרוב ניצנים",
        slug: "brussels-sprouts",
        description: "כרוב ניצנים טרי, מעולה בתנור.",
        price: 27.90,
        unit_type: "unit", // Pack
        stock_quantity: 40,
        image_url: "https://images.unsplash.com/photo-1610832958506-aa56368176cf?auto=format&fit=crop&q=80&w=800",
        category_id: "vegetables",
        is_active: true,
        is_on_sale: false,
        sale_price: null,
        created_at: new Date().toISOString(),
    },
    {
        id: "v3",
        name: "מלפפון בייבי",
        slug: "baby-cucumber",
        description: "מלפפונים קטנים ופריכים, נהדרים לנשנוש.",
        price: 12.90,
        unit_type: "pack",
        stock_quantity: 60,
        image_url: "https://images.unsplash.com/photo-1610832958506-aa56368176cf?auto=format&fit=crop&q=80&w=800",
        category_id: "vegetables",
        is_active: true,
        is_on_sale: false,
        sale_price: null,
        created_at: new Date().toISOString(),
    },

    // Dairy & Eggs
    {
        id: "d1",
        name: "מוצרלה בייבי 18%",
        slug: "mozzarella-baby",
        description: "כדורי מוצרלה קטנים, מושלמים לסלט קפרזה. מחלבות גד.",
        price: 20.90,
        unit_type: "unit",
        stock_quantity: 30,
        image_url: "https://images.unsplash.com/photo-1610832958506-aa56368176cf?auto=format&fit=crop&q=80&w=800",
        category_id: "dairy",
        is_active: true,
        is_on_sale: false,
        sale_price: null,
        created_at: new Date().toISOString(),
    },
    {
        id: "d2",
        name: "לאבנה סחוג 5%",
        slug: "labane-sbug",
        description: "לאבנה עם נגיעות סחוג פיקנטי. מחלבות גד.",
        price: 19.90,
        unit_type: "unit",
        stock_quantity: 25,
        image_url: "https://images.unsplash.com/photo-1610832958506-aa56368176cf?auto=format&fit=crop&q=80&w=800",
        category_id: "dairy",
        is_active: true,
        is_on_sale: false,
        sale_price: null,
        created_at: new Date().toISOString(),
    },

    // Bakery
    {
        id: "b1",
        name: "אוזני המן שוקולד",
        slug: "oznei-haman-choco",
        description: "אוזני המן במילוי שוקולד עשיר. המאפים של נוי.",
        price: 46.90,
        unit_type: "unit", // Pack
        stock_quantity: 50,
        image_url: "https://images.unsplash.com/photo-1610832958506-aa56368176cf?auto=format&fit=crop&q=80&w=800",
        category_id: "bakery",
        is_active: true,
        is_on_sale: false,
        sale_price: null,
        created_at: new Date().toISOString(),
    },
    {
        id: "b2",
        name: "עוגיות קפה ואגוזים",
        slug: "cookie-coffee-nuts",
        description: "עוגיות פריכות עם ארומה של קפה ושוורי אגוזים.",
        price: 46.90,
        unit_type: "unit", // Pack
        stock_quantity: 40,
        image_url: "https://images.unsplash.com/photo-1610832958506-aa56368176cf?auto=format&fit=crop&q=80&w=800",
        category_id: "bakery",
        is_active: true,
        is_on_sale: false,
        sale_price: null,
        created_at: new Date().toISOString(),
    },

    // Pantry
    {
        id: "p1",
        name: "עלי גפן של אילנה",
        slug: "vine-leaves",
        description: "עלי גפן ממולאים באורז, בטעם ביתי.",
        price: 16.90,
        unit_type: "unit",
        stock_quantity: 100,
        image_url: "https://images.unsplash.com/photo-1610832958506-aa56368176cf?auto=format&fit=crop&q=80&w=800",
        category_id: "pantry",
        is_active: true,
        is_on_sale: false,
        sale_price: null,
        created_at: new Date().toISOString(),
    },

    // Health / New
    {
        id: "h1",
        name: "סופר טופו מעושן",
        slug: "tofu-smoked",
        description: "טופו במרקם יציב בטעם מעושן עדין. משק ויילר.",
        price: 19.90,
        unit_type: "unit",
        stock_quantity: 30,
        image_url: "https://images.unsplash.com/photo-1610832958506-aa56368176cf?auto=format&fit=crop&q=80&w=800",
        category_id: "health",
        is_active: true,
        is_on_sale: false,
        sale_price: null,
        created_at: new Date().toISOString(),
    }
];
