-- ==========================================
-- SHUK BASHEHUNA - FULL DATABASE SCHEMA
-- ==========================================

-- 1. PROFILES (Users)
create table if not exists public.profiles (
  id uuid references auth.users not null primary key,
  full_name text,
  phone text,
  default_address jsonb, -- { city, street, house, floor, apt }
  is_admin boolean default false,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table public.profiles enable row level security;
create policy "Public profiles are viewable by everyone." on public.profiles for select using ( true );
create policy "Users can insert their own profile." on public.profiles for insert with check ( auth.uid() = id );
create policy "Users can update own profile." on public.profiles for update using ( auth.uid() = id );

-- 2. SITE SETTINGS (Global Config)
create table if not exists public.site_settings (
  id bigint generated by default as identity primary key,
  key text not null unique,
  value jsonb not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table public.site_settings enable row level security;
create policy "Public settings are viewable by everyone." on public.site_settings for select using ( true );
create policy "Settings are updateable by admins only." on public.site_settings for update using (
  exists ( select 1 from public.profiles where profiles.id = auth.uid() and profiles.is_admin = true )
);

-- 3. CATEGORIES (Tabs)
create table if not exists public.categories (
  id text primary key, -- slug as id (e.g. 'fruits')
  name text not null,
  sort_order integer not null default 0,
  is_visible boolean not null default true,
  image_url text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table public.categories enable row level security;
create policy "Categories are viewable by everyone." on public.categories for select using ( is_visible = true );
create policy "Categories are management by admins." on public.categories for all using (
  exists ( select 1 from public.profiles where profiles.id = auth.uid() and profiles.is_admin = true )
);

-- 4. PRODUCTS
create type unit_type_enum as enum ('kg', 'unit', 'pack');

create table if not exists public.products (
  id uuid default gen_random_uuid() primary key,
  name text not null,
  slug text not null unique,
  description text,
  price numeric not null,
  sale_price numeric,
  is_on_sale boolean default false,
  unit_type unit_type_enum not null default 'unit',
  stock_quantity integer default 0,
  image_url text,
  category_id text references public.categories(id),
  is_active boolean default true,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table public.products enable row level security;
create policy "Products are viewable by everyone." on public.products for select using ( is_active = true );
create policy "Products are management by admins." on public.products for all using (
  exists ( select 1 from public.profiles where profiles.id = auth.uid() and profiles.is_admin = true )
);

-- 5. CONTENT BLOCKS (CMS)
do $$ begin
    create type content_block_type as enum ('hero_slider', 'category_grid', 'product_carousel', 'text_banner', 'banners_grid');
exception
    when duplicate_object then null;
end $$;

create table if not exists public.content_blocks (
  id bigint generated by default as identity primary key,
  type content_block_type not null,
  title text,
  data jsonb not null default '{}'::jsonb,
  sort_order integer not null default 0,
  is_active boolean not null default true,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table public.content_blocks enable row level security;
create policy "Content blocks are viewable by everyone." on public.content_blocks for select using ( is_active = true );
create policy "Content blocks are management by admins." on public.content_blocks for all using (
  exists ( select 1 from public.profiles where profiles.id = auth.uid() and profiles.is_admin = true )
);

-- 6. ORDERS
create table if not exists public.orders (
  id uuid default gen_random_uuid() primary key,
  user_id uuid references auth.users(id),
  status text not null default 'pending', -- pending, paid, preparing, shipping, completed, cancelled
  total_price_estimated numeric not null,
  total_price_final numeric,
  shipping_address jsonb not null,
  delivery_slot_start timestamp with time zone,
  delivery_slot_end timestamp with time zone,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table public.orders enable row level security;
create policy "Users can view own orders." on public.orders for select using ( auth.uid() = user_id );
create policy "Users can insert own orders." on public.orders for insert with check ( auth.uid() = user_id );
create policy "Admins can view all orders." on public.orders for select using (
  exists ( select 1 from public.profiles where profiles.id = auth.uid() and profiles.is_admin = true )
);

-- 7. ORDER ITEMS
create table if not exists public.order_items (
  id uuid default gen_random_uuid() primary key,
  order_id uuid references public.orders(id) not null,
  product_id uuid references public.products(id) not null,
  quantity_ordered numeric not null,
  quantity_actual numeric,
  price_at_order numeric not null,
  total_item_price numeric,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table public.order_items enable row level security;
create policy "Users can view own order items." on public.order_items for select using (
  exists ( select 1 from public.orders where orders.id = order_items.order_id and orders.user_id = auth.uid() )
);
create policy "Users can insert own order items." on public.order_items for insert with check (
  exists ( select 1 from public.orders where orders.id = order_items.order_id and orders.user_id = auth.uid() )
);

-- ==========================================
-- INITIAL DATA MIGRATION
-- ==========================================

-- Categories
insert into public.categories (id, name, sort_order) values
('fruits', 'פירות', 10),
('vegetables', 'ירקות', 20),
('new', 'חדש על המדף', 30),
('dairy', 'מקרר, חלב וביצים', 40),
('bakery', 'המאפייה', 50),
('pantry', 'המזווה', 60),
('deli', 'המעדנייה', 70),
('snacks', 'חטיפים ומשקאות', 80),
('health', 'בריאות', 90),
('home', 'לבית ולמטבח', 100),
('kids', 'ילדים', 110),
('winter', 'חורף חם', 120),
('specials', 'מבצעים', 130)
on conflict (id) do update set name = excluded.name;

-- Products (Sample)
insert into public.products (name, slug, description, price, unit_type, stock_quantity, category_id, image_url, is_on_sale, sale_price) values
('תות שדה - מארז 1 ק״ג', 'strawberry-pack', 'תות שדה מתוק ואדום, טרי מהשדה.', 49.90, 'unit', 50, 'fruits', 'https://images.unsplash.com/photo-1464965911861-746a04b4b0ae', true, NULL),
('אגס ישראלי', 'israeli-pear', 'אגס עסיסי ומתוק מתוצרת הארץ.', 24.90, 'kg', 100, 'fruits', 'https://images.unsplash.com/photo-1615484477778-ca3b77940c25', false, NULL),
('עגבניות סופי', 'tomato-maggie', 'עגבניות בטעם של פעם.', 29.90, 'kg', 80, 'vegetables', 'https://images.unsplash.com/photo-1592924357228-91a4daadcfea', true, 24.90),
('מוצרלה בייבי 18%', 'mozzarella-baby', 'כדורי מוצרלה קטנים.', 20.90, 'unit', 30, 'dairy', 'https://images.unsplash.com/photo-1486297678162-eb2a19b0a32d', false, NULL)
on conflict (slug) do nothing;

-- Content Blocks
insert into public.content_blocks (type, title, sort_order, data) values
('hero_slider', 'Main Hero', 10, '{"slides": [{"link": "/category/fruits", "title": "הפירות הכי מתוקים העונה", "subtitle": "ישירות מהחקלאי אליכם", "image_url": "https://images.unsplash.com/photo-1542838132-92c53300491e", "button_text": "הזמינו עכשיו"}]}'),
('category_grid', 'Categories', 20, '{}'),
('product_carousel', 'Best Sellers', 30, '{"limit": 10, "category_id": "specials"}')
on conflict do nothing;

-- Site Settings
insert into public.site_settings (key, value) values
('announcement_bar', '{"text": "משלוח חינם בקנייה מעל 300 ₪ 🚚", "is_active": true}')
on conflict (key) do nothing;
